#!/usr/bin/env python3
"""
gen_barrett_vectors.py

Deterministic generator for the scalar Barrett reduction test vectors.

The C implementation in src/adapters/scalar/redc/barrett.c computes:

    mu     = floor(2^64 / q)
    reduce(x, q, mu) = x mod q       (canonical for x < 2^64, q < 2^32)
    mul(a, b, q, mu) = (a * b) mod q
    modpow(b, e, q)  = b^e mod q

This script recomputes the same quantities with Python arbitrary-precision
integers, i.e., an independent reference, and outputs them as a C header. The
tests include that header for deterministic, hermetic regression vectors.

Regenerate (and re-run the tests) whenever the vector set changes:

    python3 tests/unittests/vectors/gen_barrett_vectors.py

The output is fully deterministic: the PRNG below is seeded with a fixed
constant.
"""

import random

M64_MAX = (1 << 64) - 1

# Canonical NTT primes used by PQC/Kyber/Dilithium-style schemes, plus
# boundary values of q that stress the mu derivation and the reduction path.
MODULI = [
    2, 3, 5, 113, 3329, 7681, 12289, 1048573, 7340033, 8380417, 4294967291,
    4294967295,
]

_rng = random.Random(0xAFF0CE)


def c_u32(v):
    return f"{v}u"


def c_u64(v):
    return f"UINT64_C({v})"


def reduce_boundary_values(q):
    """Boundary inputs for reduce: around 0, q, 2q and the 64-bit limits."""
    q2 = q * q
    xs = {0, 1, q - 1, q, q + 1, 2 * q - 1, 2 * q, q2 - 1, M64_MAX}
    return sorted(x for x in xs if 0 <= x <= M64_MAX)


def emit_array(name, rows):
    """Emit an initializer list in the repo's clang-format layout.

    One initializer per line; rows longer than 80 columns are broken with
    each field on its own line aligned to the opening brace (the layout
    clang-format with AlignAfterOpenBracket: Align produces).
    """
    lines = []
    for row in rows:
        row_text = "{%s}" % ", ".join(row)
        if len("    " + row_text + ",") <= 80:
            lines.append("    %s," % row_text)
        else:
            lines.append("    {%s," % row[0])
            lines.extend("     %s," % field for field in row[1:-1])
            lines.append("     %s}," % row[-1])
    return "static const %s[] = {\n%s\n};" % (name, "\n".join(lines))


def main():
    out = []
    out.append("/*")
    out.append(" * barrett_vectors.h")
    out.append(" * Auto-generated by gen_barrett_vectors.py -- DO NOT EDIT.")
    out.append(" * Regenerate with: python3 tests/unittests/vectors/gen_barrett_vectors.py")
    out.append(" */")
    out.append("")
    out.append("#ifndef BARRETT_VECTORS_H")
    out.append("#define BARRETT_VECTORS_H")
    out.append("")
    out.append("#include <stdint.h>")
    out.append("")

    out.append("typedef struct {")
    out.append("    uint32_t q;")
    out.append("    uint64_t mu;")
    out.append("} barrett_mu_vector;")
    out.append("")
    out.append("typedef struct {")
    out.append("    uint32_t q;")
    out.append("    uint64_t mu;")
    out.append("    uint64_t x;")
    out.append("    uint64_t expected;")
    out.append("} barrett_reduce_vector;")
    out.append("")
    out.append("typedef struct {")
    out.append("    uint32_t q;")
    out.append("    uint64_t mu;")
    out.append("    uint32_t a;")
    out.append("    uint32_t b;")
    out.append("    uint32_t expected;")
    out.append("} barrett_mul_vector;")
    out.append("")
    out.append("typedef struct {")
    out.append("    uint32_t q;")
    out.append("    uint64_t mu;")
    out.append("    uint32_t base;")
    out.append("    uint32_t exp;")
    out.append("    uint32_t expected;")
    out.append("} barrett_modpow_vector;")
    out.append("")

    # mu vectors -----------------------------------------------------------
    mu_rows = []
    for q in MODULI:
        mu = (1 << 64) // q
        mu_rows.append((c_u32(q), c_u64(mu)))
    out.append(f"#define BARRETT_MU_VECTORS_COUNT {len(mu_rows)}u")
    out.append(emit_array("barrett_mu_vector BARRETT_MU_VECTORS", mu_rows))
    out.append("")

    # reduce vectors (in-domain: x < q^2) ----------------------------------
    red_rows = []
    neg_rows = []
    for q in MODULI:
        mu = (1 << 64) // q
        q2 = q * q
        for x in reduce_boundary_values(q):
            row = (c_u32(q), c_u64(mu), c_u64(x), c_u64(x % q))
            if x < q2:
                red_rows.append(row)
            else:
                neg_rows.append(row)
        for _ in range(4):
            x = _rng.randrange(q2)
            red_rows.append((c_u32(q), c_u64(mu), c_u64(x), c_u64(x % q)))
        for _ in range(2):
            x = q2 + _rng.randrange(M64_MAX - q2 + 1)
            neg_rows.append((c_u32(q), c_u64(mu), c_u64(x), c_u64(x % q)))
    out.append(f"#define BARRETT_REDUCE_VECTORS_COUNT {len(red_rows)}u")
    out.append(emit_array("barrett_reduce_vector BARRETT_REDUCE_VECTORS",
                          red_rows))
    out.append("")
    out.append(f"#define BARRETT_REDUCE_NEGATIVE_VECTORS_COUNT {len(neg_rows)}u")
    out.append(emit_array(
        "barrett_reduce_vector BARRETT_REDUCE_NEGATIVE_VECTORS", neg_rows))
    out.append("")

    # mul vectors (canonical operands) --------------------------------------
    mul_rows = []
    for q in MODULI:
        mu = (1 << 64) // q
        pairs = [(0, 0), (1, 1), (1, q - 1), (q - 1, q - 1), (2, 3)]
        pairs += [(_rng.randrange(q), _rng.randrange(q)) for _ in range(3)]
        for a, b in pairs:
            mul_rows.append((c_u32(q), c_u64(mu), c_u32(a), c_u32(b),
                             c_u32((a * b) % q)))
    out.append(f"#define BARRETT_MUL_VECTORS_COUNT {len(mul_rows)}u")
    out.append(emit_array("barrett_mul_vector BARRETT_MUL_VECTORS", mul_rows))
    out.append("")

    # modpow vectors --------------------------------------------------------
    pow_rows = []
    for q in MODULI:
        mu = (1 << 64) // q
        cases = [(0, 0), (0, 5), (1, 0xFFFFFFFF), (2, 0), (2, 1),
                 (q - 1, 2), (q - 1, 3), (3, q - 2), (2, 0xFFFFFFFF)]
        cases += [(_rng.randrange(q), _rng.randrange(1 << 32))
                  for _ in range(2)]
        for base, exp in cases:
            pow_rows.append((c_u32(q), c_u64(mu), c_u32(base), c_u32(exp),
                             c_u32(pow(base, exp, q))))
    out.append(f"#define BARRETT_MODPOW_VECTORS_COUNT {len(pow_rows)}u")
    out.append(emit_array("barrett_modpow_vector BARRETT_MODPOW_VECTORS",
                          pow_rows))
    out.append("")

    out.append("#endif /* BARRETT_VECTORS_H */")
    print("\n".join(out))


if __name__ == "__main__":
    main()
